
import type { Metadata } from "next";
import { Toaster } from 'react-hot-toast'
import "./globals.css";


export const metadata: Metadata = {
  title: "MemeBuzz - Team .EXE ",
  description: "Generated by create next app",
};


function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-black">
      <main>

        {children}

      </main>
      <Toaster />
    </body>
    </html>
  )
}

export default Layout;

